### PR TITLE
fix: broken links in api for react and vue

### LINKED ISSUE #736: Broken Link
**Describe the bug**
I find out a broken link in the documentation

**To Reproduce**
1. Go to 'https://testing-library.com/docs/react-testing-library/api#debug'
2. Click on 'DOM Testing Library' below the code snippet.
3. See link is broken

### PR DESCRIPTION
**Pull request by MatanBobi**
Resolves #736.

### CODE REVIEW

**Review by eps1lon — COMMENTED** [review]
Question: Broken as in "they return 404" or broken as in "they return 301"? 

We need to add redirects as well to fix all existing links that we don't control as well.

**Comment by MatanBobi** [comment]
> Question: Broken as in "they return 404" or broken as in "they return 301"?
> 
> We need to add redirects as well to fix all existing links that we don't control as well.

They return 404. There's no redirect mechanism for those urls since they are just leading to a place that doesn't exist.
The problem is that on build time docusaurus understands that it can't find the markdown file (since dom-testing-library/api-queries.mdx doesn't exist anymore) so it adds that route to the current location(docs/react-testing-library/dom-testing-library/api-queries.mdx), so creating a redirect rule might be problematic because there are many cases we'd need to solve.

**Comment by eps1lon** [comment]
> There's no redirect mechanism for those urls since they are just leading to a place that doesn't exist.

With [netlify you can create redirects](https://docs.netlify.com/routing/redirects/).

I'd be shocked if docosaurus has no API to move a page. That's a fundamental part of the web.

**Comment by MatanBobi** [comment]
They do have, what I'm trying to say is that you need to predict the broken url so you'll be able to redirect it to the right page or redirect to a fallback page.
What I'm trying to say is that whenever we delete a markdown file/remove it, the urls that docusaurus generate will lead to a broken page if not fixed, that's the case we had here.

**Comment by alexkrolick** [comment]
I added the redirects here: 
https://github.com/testing-library/testing-library-docs/blob/master/netlify.toml#L57-L59

But I think @MatanBobi is saying the URL is malformed if you reference the deleted .mdx..md files so the redirect doesn't even kick in

**Comment by MatanBobi** [comment]
> I added the redirects here: 
> https://github.com/testing-library/testing-library-docs/blob/master/netlify.toml#L57-L59
> 
> But I think @MatanBobi is saying the URL is malformed if you reference the deleted .mdx..md files so the redirect doesn't even kick in

Exactly, thanks @alexkrolick :)

**Pull request merged**
