### PR TITLE
Update docusaurus version

### LINKED ISSUE #991: 301 redirection to pages with trailing /
**Describe the bug** A clear and concise description of what the bug is.

When you go to the documentation for GitHub link or some just open the page and hard-refresh server reports 301 redirection to page with trailing `/` in the uri:

image

All seems to be fine, as page is rendered, menu links works, but some links in are broken.

**To Reproduce** Steps to reproduce the behavior:

- open: https://testing-library.com/docs/user-event/intro
- you'll be redirected to page with trailing / (see dev tools to see 301 redirection)
- try to click `You can find the docs for user-event@13.5.0 here.`
- you'll get 404 page - https://testing-library.com/docs/user-event/ecosystem-user-event:

image

**Expected behavior** A clear and concise description of what you expected to
happen.

Either there is no redirection to pages with trailing `/`;
or links are rendered correctly wither for pages with `/` or without.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by timdeschryver**
# What's in this PR

Update docusaurus version for the following reasons:

## feat: enable respectPrefersColorScheme

With this PR the website uses the user's system theme to set the default theme.

It's set via the docusaurus config `colorMode.respectPrefersColorScheme`.
Because this setting isn't available on our current version, I had to upgrade docusaurus to the latest version, which seems to be working fine.

## fix: broken links (when URL ends with a slash)

Closes #991
Closes #985

### CODE REVIEW

**Review by alexkrolick — APPROVED** [review]

**Comment by alexkrolick** [comment]
Looks like we need to fix the build config, it says "minimal Node version not met"

**Comment by MatanBobi** [comment]
> Looks like we need to fix the build config, it says "minimal Node version not met"

Yeah I think we have two options here, either push an `.nvmrc` or `.node-version` file to the repo or ask Kent to upgrade the version manually (because I think he's the only one with netlify permissions).

About the upgrade, I remember giving it a try and something broke. Sorry for the obvious question, but have you also tried to run `build` locally?

If everything works properly, this is a no-brainer :)

**Comment by timdeschryver** [comment]
Oh yikes, thanks for the calling me out on this - I didn't follow up on this PR after it was created.
I'll take a look at when I can do about it soon.

Locally, it does work (start, build, serve)
image

**Comment by timdeschryver** [comment]
Seems like to be working by setting the node.js version in a `.nvmrc` file.
I don't got time now, but I'll check the preview tomorrow.

**Comment by timdeschryver** [comment]
Also note that beta v14 logs a warning in the console while building the app. That should be resolved in the next v15 version. Maybe that we should wait, so there won't be any confusion around this. AFAIK they should release that soon.

**Comment by MatanBobi** [comment]
> Seems like to be working by setting the node.js version in a `.nvmrc` file. I don't got time now, but I'll check the preview tomorrow.

The preview looks good to me though I did find a change in the CSS design for `details` component:
https://deploy-preview-986--testing-library.netlify.app/docs/dom-testing-library/faq
Vs
https://testing-library.com/docs/dom-testing-library/faq

This looks actually better IMO but just wanted to point that out.
Also, I'm not sure I like the `.nvmrc` file over `.node-version` since the first implies that we're using nvm for some reason.
Wdyt?

Btw, I ran `npm run build` locally and didn't see any warnings, what was the warning you saw?

**Comment by timdeschryver** [comment]
Nice find @MatanBobi !
Both nvm and node-version works (and are mentioned in the docs), I went for nvm because I'm using it too. I will change it to node-version if you prefer that.

It's `npm run start` command that shows the warning, but it isn't breaking.

**Comment by MatanBobi** [comment]
> Nice find @MatanBobi ! Both nvm and node-version works (and are mentioned in the docs), I went for nvm because I'm using it too. I will change it to node-version if you prefer that.
> 
> It's `npm run start` command that shows the warning, but it isn't breaking.

Oh, if you're using nvm we can keep `.nvmrc` :)
I think this is ready for merge IMO, is there something holding us back?

Btw, I highly recommend moving to [`fnm`](https://github.com/Schniz/fnm), it's much faster than `nvm`. I moved and didn't look back since :)

**Comment by timdeschryver** [comment]
I guess I'm now on `fnm` too 😅 (thanks for the tip), that's actually what I was looking for (I tried volta but I didn't like it). 
I've also tried to revert the details style, but it's still not the same.
If you're happy with itt, feel free to merge this.

**Comment by MatanBobi** [comment]
@timdeschryver This looks good to me :) You can merge if you're good with it too.

**Review by MatanBobi — APPROVED** [review]

**Comment by timdeschryver** [comment]
@MatanBobi sorry, one more change to revert the `trailingSlash`.
I would prefer not to change this (or maybe later), since a better solution would be to append the `.mdx` extension to all links. I haven't thought of it, but this allows us to navigate in the docs via the GitHub interface (#996).

**Comment by MatanBobi** [comment]
@all-contributors please add @timdeschryver for code :)

**Pull request merged**
