### PR TITLE
Add feeds

### LINKED ISSUE #670: RSS feed for the blog
**Is your feature request related to a problem? Please describe.**
I can't find an RSS or any other kind of feed for the blog. Am I missing something or is there no feed. Would love to be able to subscribe for updates.

**Describe the solution you'd like**
Adding federation to allow subscribing to the blog

### PR DESCRIPTION
**Pull request by nickmccurdy**
Docusaurus supports RSS and Atom feeds but we haven't enabled them

### CODE REVIEW

**Comment by nickmccurdy** [comment]
All the descriptions seem to be truncated to only a few words and I'm not seeing a config option for the feed generation.

```xml
<description>
<![CDATA[ Hello friends! I'm pleased to announce the recent updates to the testing-library ]]>
</description>
```

Is there a way to disable that?

**Comment by MatanBobi** [comment]
> All the descriptions seem to be truncated to only a few words and I'm not seeing a config option for the feed generation.
> 
> ```
> <description>
>   <![CDATA[ Hello friends! I'm pleased to announce the recent updates to the testing-library ]]>
> </description>
> ```
> 
> Is there a way to disable that?

I think it's possible by adding a truncate comment in the md file that will signal where to truncate the post :)
```
<!--truncate-->
```

**Comment by nickmccurdy** [comment]
I'm aware, but ideally it would be nice to show the full article, especially since we're not worried about monetization or retention

**Comment by MatanBobi** [comment]
Well, I couldn't find anything on the documentation nor in the [code](https://github.com/facebook/docusaurus/blob/498f8a0f27f775438d9452b0ba193a5b3bc3afb4/packages/docusaurus-plugin-content-blog/src/blogUtils.ts#L38).
Maybe we can suggest them if we find it necessary and I think I'll be able to create a PR for that.

**Comment by nickmccurdy** [comment]
Yea could be a good thing do check on upstream. Should we do that first or merge for now?

**Comment by MatanBobi** [comment]
IMO we can merge this for now and I can open an issue there to see if they'd like me to raise a PR to add that.

**Pull request merged**
