### PR TITLE
doc(svelte): add link to svelte-society/recipes-mvp/testing

### PR DESCRIPTION
**Pull request by sastan**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks like that document could be updated to use the latest best practices: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library

**Comment by kentcdodds** [comment]
Would you be interested in making a pull requires on that repository to do that?

**Comment by kentcdodds** [comment]
@all-contributors please add @sastan for docs

**Comment by sastan** [comment]
Sure. I put that on my list. Can i ping you for a review once i have incorporated the changes.

Thank you for the great work you providing to the developer community!

**Comment by kentcdodds** [comment]
You can definitely ping me. But you should probably also ping folks in https://testing-library.com/discord 😀

**Comment by sastan** [comment]
Will do.

**Comment by sastan** [comment]
Will do.

**Pull request merged**
