### PR TITLE
change text cursor to pointer cursor

### PR DESCRIPTION
**Pull request by iqbal125**
hovering over each question in the faq, results in the cursor changing to a text cursor. I have added a simply style attribute of pointer: cursor and id to each summary.

### CODE REVIEW

**Comment by alexkrolick** [comment]
There are several more usages of summary/details tags on different pages in the docs - can you explain why the default is confusing and/or suggest a fix that works everywhere?

**Comment by iqbal125** [comment]
@alexkrolick So hovering over the summary links turns the cursor to a text pointer, which makes it seem like its not clickable, but it is clickable. 

so adding a simply style to make the cursor a pointer will make it easy for everyone to see that it is clickable. 

Only for this page I cant speak for the rest of the docs

**Comment by afontcu** [comment]
I kind of agree with the idea of the PR - `<summary>` provides a text cursor style, and it might be confusing.

However, it is true that we should find a way to style all `<summary>` elements of the docs, not only the ones in React section. Maybe a simple element styling in `/website/static/css/custom.css`?

```css
details summary {
  cursor: pointer;
}
```


What do you think about that?

**Comment by alexkrolick** [comment]
@afontcu maybe scope that to the article class if there is one

**Comment by afontcu** [comment]
Hi @iqbal125! Did you get a chance to look into this?

**Comment by iqbal125** [comment]
hello again @afontcu, I made changes based on feedback. I also updated my other PRs, do you mind taking a look?

**Comment by alexkrolick** [comment]
Thank you for the update!

**Pull request merged**
