### PR TITLE
Update example-react-router.md

### PR DESCRIPTION
**Pull request by arturoromeroslc**
The first example test did not pass because we expected the element to be a heading not a div. 
Next the assertion for a no match route is 404 Not Found

### CODE REVIEW

**Comment by alexkrolick** [comment]
Something is up with the Docusaurus build

**Comment by kentcdodds** [comment]
Let's just merge it and hope it works 🤞 If not then we can look into fixing things.

**Comment by kentcdodds** [comment]
@all-contributors please add @arturoromeroslc for docs

**Comment by kentcdodds** [comment]
Whoops, made that too soon.

**Comment by kentcdodds** [comment]
@all-contributors please add @arturoromeroslc for docs

**Pull request merged**
