### PR TITLE
docs: add testing-library-selector to ecosystem

### PR DESCRIPTION
**Pull request by domasx2**
Hi! Thanks for a great testing lib. Wrote a small lib for reusable selectors https://github.com/domasx2/testing-library-selector

### CODE REVIEW

**Review by nickmccurdy — APPROVED** [review]
This example and your library look good thanks.

**Pipe dream:** Maybe it would be simpler if we just curried all of the query functions. If anyone's interested I can try to make an alternate API.

**Comment by domasx2** [comment]
thanks! rebased on latest master

**Comment by domasx2** [comment]
> Pipe dream: Maybe it would be simpler if we just curried all of the query functions. If anyone's interested I can try to make an alternate API.

**Comment by domasx2** [comment]
> Pipe dream: Maybe it would be simpler if we just curried all of the query functions. If anyone's interested I can try to make an alternate API.

I've been thinking about something similar... There's a common use case where I want to scope queries to a particular container, typically identified with a `data-testid`. 
Currently we typically get the container dom node, then query against it. However, sometimes React will recreate the container dom node or elements, making the old dom node reference stale. So I'm toying with the idea to extend this library with smth like this:
```
const inputInContainer = byTestId('foo-container').byLabelText('my input')
```
then `inputInContainer.get()` would get the container first, if that succeeds, get the input inside it, and so on

**Comment by nickmccurdy** [comment]
@all-contributors add @domasx2 for docs

**Pull request merged**
