### PR TITLE
fixed typo error

### PR DESCRIPTION
**Pull request by mrtyagi07**
### Fixes typo in impactful-conribution.png

I noticed a typo in the impactful-conribution.png file where it says "conribution" instead of "contribution". I fixed the typo and this pull request includes the corrected version of the file.

### CODE REVIEW

**Comment by akoskm** [comment]
I believe you should also fix the now outdated reference it https://github.com/testing-library/testing-library-docs/blob/0d7aa8e8871f6f78d9c3e19d5ac3340d4f74d3b1/src/pages/index.js#L272

**Comment by mrtyagi07** [comment]
> I believe you should also fix the now outdated reference it
> 
> https://github.com/testing-library/testing-library-docs/blob/0d7aa8e8871f6f78d9c3e19d5ac3340d4f74d3b1/src/pages/index.js#L272

Thank you, Akos, for pointing that out. I have fixed it

**Review by timdeschryver — APPROVED** [review]
Seems like https://osawards.com is down 🤔

**Comment by timdeschryver** [comment]
@all-contributors please add @mrtyagi07 for docs

**Pull request merged**
