### PR TITLE
Added company user for Testing library

### PR DESCRIPTION
**Pull request by AshifMohammad**
Added Company which uses it

### CODE REVIEW

**Review by AshifMohammad — COMMENTED** [review]
LGTM

**Comment by AshifMohammad** [comment]
@afontcu Hello i saw you have been reviewing PRs , could you please take a look at this? 
Simple change to add the company which uses it, that's my company CDK Global Inc. and we have moved entirely on React Testing Library. 🐐

**Review by nickmccurdy — CHANGES_REQUESTED** [review]
Can you please make the background of the image transparent so it's consistent with the other icons?

**Comment by nickmccurdy** [comment]
Also the home page company list is now broken onto a second line, I'm not sure how to fix that.

**Comment by alexkrolick** [comment]
@nickmccurdy the user list is a full-width element that wraps as needed

**Comment by AshifMohammad** [comment]
@nickmccurdy Sure. I made changes.
 Thanks for the suggestions

**Comment by nickmccurdy** [comment]
Please resolve the merge conflicts.

**Comment by MatanBobi** [comment]
@AshifMohammad Can you please resolve the conflicts so we'll be able to merge this one? :)

**Comment by AshifMohammad** [comment]
@nickmccurdy @MatanBobi , Sorry for the delayed response :) . I resolved the merge conflicts. 
Thanks for reviewing the PR. Loved RTL btw 🙏🏼

**Comment by MatanBobi** [comment]
Hi @AshifMohammad, thanks for the feedback :)
Regarding this PR, the companies using this have moved to a different place and they now reside here:
https://github.com/testing-library/testing-library-docs/blob/master/docusaurus.config.js#L19

Please add it there and revert the `siteConfig` file since it's an old file and was removed in our refactor :)

**Comment by AshifMohammad** [comment]
@MatanBobi Thank you for the input, i refactored it and added the correct location in `.docusaurus.config.js`.

**Comment by MatanBobi** [comment]
> @MatanBobi Thank you for the input, i refactored it and added the correct location in `.docusaurus.config.js`.

Thanks. Though I can still see the`siteConfig` file, you need to remove it.

**Comment by AshifMohammad** [comment]
@MatanBobi Apologies, i should have removed it as we moved to docusaurus :) . I updated the PR. Thanks

**Comment by AshifMohammad** [comment]
@MatanBobi @nickmccurdy could you please review the PR?

**Comment by AshifMohammad** [comment]
@nickmccurdy Hi , Could i get some of your time to review this PR please? i am happy to make some more changes if required :) , Thanks

**Review by nickmccurdy — CHANGES_REQUESTED** [review]
Thanks. The only remaining issue I'm seeing is that the logo has white spots on a dark background. Do you have a fully transparent or SVG version we could use?
image

**Comment by AshifMohammad** [comment]
> Thanks. The only remaining issue I'm seeing is that the logo has white spots on a dark background. Do you have a fully transparent or SVG version we could use?
> image

@nickmccurdy , Nick this is the official logo i could get for this use. I am afraid if i could have the fully transparent logo. 
meanwhile i will try to get the logo and raise another PR for that?

**Comment by MatanBobi** [comment]
I'm closing this one as there was no progress for a year now. To merge this, we'll need an SVG version. Please feel free to create another PR :)

**Pull request closed without merging**
