### PR TITLE
docs: update angular api

### PR DESCRIPTION
**Pull request by timdeschryver**
This PR removes the methods that were removed in the last version of ATL.

Closes https://github.com/testing-library/angular-testing-library/issues/182

### CODE REVIEW

**Review by MatanBobi — APPROVED** [review]
LGTM,
Just a small question, why aren't we using destructure for all the render results as we do in RTL's docs?

**Comment by timdeschryver** [comment]
Good question @MatanBobi 
This can be updated as well, earlier ATL didn't have `screen` and I found it easier not to deconstruct the result. 
I'll update the docs for this later this week 👍

**Comment by MatanBobi** [comment]
Cool @timdeschryver lmk if I can assist :)

**Comment by timdeschryver** [comment]
@MatanBobi I've updated the examples, thanks again to bring this to our attention

**Comment by MatanBobi** [comment]
Looks great @timdeschryver want me to merge it? :)

**Comment by timdeschryver** [comment]
@MatanBobi feel free to merge this in 🙂
Thanks again for the review!

**Pull request merged**
