### PR TITLE
fix(userEvent): setup borken link

### PR DESCRIPTION
**Pull request by moshfeu**
It fixes the link in Github. ~I'm not sure if it's gonna fix the [link on the website](https://testing-library.com/docs/user-event/intro/#:~:text=recommend%20to%20use-,userEvent.setup(),-when%20rendering%20your)~

https://deploy-preview-996--testing-library.netlify.app/docs/user-event/setup

### CODE REVIEW

**Review by timdeschryver — COMMENTED** [review]
Thanks for creating this PR.
This is part of a broader problem because multiple links seem to be broken.

Could you try the preview in #986, it should contain a global fix.

**Review by timdeschryver — APPROVED** [review]
> It fixes the link in Github

That's something that I didn't think of, thanks!

**Comment by timdeschryver** [comment]
@all-contributors please add @moshfeu for docs

**Comment by moshfeu** [comment]
Thank you @timdeschryver ❤️

**Pull request merged**
