### PR TITLE
Update migrate-from-enzyme.mdx

### PR DESCRIPTION
**Pull request by vier31**
Found some spelling and grammar errors, so I took the liberty to fix them.

### CODE REVIEW

**Review by MatanBobi — APPROVED** [review]
Looks good, thanks! 👍

**Comment by MatanBobi** [comment]
@all-contributors please add @vier31 for docs

**Comment by vier31** [comment]
Thanks so much. This was my first ever pull request in the wild. 🥳

**Comment by MatanBobi** [comment]
> Thanks so much. This was my first ever pull request in the wild. 🥳

Good job, keep it up then :)

**Pull request merged**
