### PR TITLE
docs: add webdriverio-testing-library intro

### PR DESCRIPTION
**Pull request by olivierwilkinson**
I wasn't sure about the process around this but figured opening a PR was a good start.

This is a first draft of an intro page for [webdriverio-testing-library](https://github.com/testing-library/webdriverio-testing-library). I tried to keep the structure similar to the docs for other frameworks.

Any edits/suggestions would be much appreciated! 😄

### CODE REVIEW

**Comment by MatanBobi** [comment]
Hi @olivierwilkinson! :) Thanks for this.
Is there a reason no to use ES Modules in the code examples?
Also, I would use backticks before the APIs to show that they are code sections.

**Comment by olivierwilkinson** [comment]
> Hi @olivierwilkinson! :) Thanks for this.

No worries 😄

> Is there a reason no to use ES Modules in the code examples?

No good reason, I've updated the examples 👍

> Also, I would use backticks before the APIs to show that they are code sections.

Good idea - I also renamed the "Usage" heading to "API" because that seemed clearer to me when reading it again.

**Review by MatanBobi — APPROVED** [review]
LGTM 👍🏻
I'm merging this one.
Thanks!

**Comment by MatanBobi** [comment]
@all-contributors please add @olivierwilkinson for docs :)

**Pull request merged**
