### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **17%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /website/static/img/users/facebook-open-source.png | 16.68kb | 8.07kb | 51.60% |
| /website/static/img/svelte-logo.png | 7.73kb | 4.18kb | 45.91% |
| /website/static/img/react-native-128x128.png | 5.92kb | 3.38kb | 42.96% |
| /website/static/img/react-128x128.png | 14.22kb | 9.36kb | 34.17% |
| /website/static/img/reason-200x200.png | 2.46kb | 1.76kb | 28.15% |
| /website/static/img/preact-128x128.png | 10.97kb | 8.22kb | 25.06% |
| /website/static/img/nightwatch-128x128.png | 15.92kb | 11.94kb | 25.01% |
| /website/static/img/users/expediagroup.svg | 12.25kb | 9.31kb | 24.01% |
| /website/static/img/users/walmart.png | 30.90kb | 23.84kb | 22.87% |
| /website/static/img/users/wix.svg | 9.46kb | 7.67kb | 18.94% |
| /website/static/img/eslint-plugin-screenshot.png | 36.30kb | 29.50kb | 18.73% |
| /website/static/img/testcafe-128x128.jpg | 3.79kb | 3.15kb | 16.78% |
| /website/static/img/testingjavascript.jpg | 228.22kb | 196.34kb | 13.97% |
| /website/static/img/users/paypal.svg | 6.30kb | 5.59kb | 11.18% |
| /website/static/img/users/sweepbright.svg | 8.59kb | 7.64kb | 11.02% |
| /website/static/img/cypress-128x128.png | 12.91kb | 11.62kb | 10.02% |
| /website/static/img/users/parsleyhealth.svg | 5.49kb | 5.01kb | 8.66% |
| /website/static/img/users/testsigma.svg | 11.16kb | 10.37kb | 7.05% |
| /website/static/img/users/travelperk.svg | 14.21kb | 13.36kb | 6.05% |
| /website/static/img/users/codecademy.svg | 10.40kb | 9.81kb | 5.64% |
| /website/static/img/users/velopayments.svg | 1.79kb | 1.69kb | 5.57% |
| /website/static/img/users/tiller.svg | 8.61kb | 8.52kb | 1.05% |
| /website/static/img/users/intellihr.svg | 1.84kb | 1.84kb | 0.05% |
| /website/static/img/users/autodesk.svg | 4.56kb | 4.56kb | 0.02% |
| | | | |
| **Total :** | **480.69kb** | **396.74kb** | **17.46%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by kentcdodds** [comment]
Thanks. I've got it setup on this repo now.

**Comment by kentcdodds** [comment]
Oh, jk. I thought this was a different repo. It'd be neat to have this on the testing-library-docs repo, but they charge for that (even for oss 😦).

**Comment by MichaelDeBoey** [comment]
@kentcdodds I haven't found anything about a charge? 🤔

**Comment by MichaelDeBoey** [comment]
Oh now I see...
Schermafbeelding 2019-10-28 om 22 03 32

Every organization needs to pay?

**Comment by MichaelDeBoey** [comment]
Maybe @dabutvin can help you out with providing a free license for all the open source organizations? 🤔

**Comment by dabutvin** [comment]
Hey there! Imgbot is free for all OSS whether it is a personal account or an organization.

Just choose the open source option in that screenshot and pick the organization you would like to install in.

Let me know if you have any trouble and we'll get it sorted 👍

**Comment by kentcdodds** [comment]
Ah! Thanks @dabutvin! Appreciate you building this and making it free for open source 💯

**Pull request merged**
