### PR TITLE
Update ecosystem-user-event.mdx

### PR DESCRIPTION
**Pull request by rickysullivan-gallagher**
Minor change to set `element` before expecting something of it.

### CODE REVIEW

**Comment by MatanBobi** [comment]
Hi @rickysullivan-gallagher!
Thanks for taking the time to putting this together.
I don't think this one is really necessary, as long as the element is used only once, I find this redundant.
Thanks again! :)

**Comment by rickysullivan** [comment]
What is element then?

**Comment by MatanBobi** [comment]
@rickysullivan My bad, I didn't see the assertion because it wasn't changed..
Thanks!

**Comment by MatanBobi** [comment]
@rickysullivan which user do you want me to add to the contributors list?

**Comment by rickysullivan** [comment]
@rickysullivan is fine. I didn't realise I had forked using my work account.

**Comment by MatanBobi** [comment]
No worries, thanks for taking care of this.

@all-contributors please add @rickysullivan for docs :)

**Pull request merged**
