### PR TITLE
Fixed grid layout

### PR DESCRIPTION
**Pull request by AldinRekic**
Margin of first and last grid item shift top and bottom row layout off-center.

### CODE REVIEW

**Comment by MatanBobi** [comment]
Hi @AldinRekic!
Thanks for the contribution.
Can you please share a screenshot for the before and after your changes?

**Comment by AldinRekic** [comment]
Hey @MatanBobi! Here are the Screenshots!  

Before:
beforeChange
After:
afterChange

**Review by timdeschryver — APPROVED** [review]
You got a sharp eye! 👍

**Comment by alexkrolick** [comment]
Thanks - would it be possible to align the text baselines as well, while you're here? 🙏

**Comment by AldinRekic** [comment]
@alexkrolick Svelte, React and React Native images are not 80x80 like the rest. Svelte width is under 80px but width doesn't cause vertical text shift. React and React Native (both are 80x73) images are causing the text baseline to shift. I would adjust all 3 images to have it nicely standardized (even though Svelte image doesn't cause any issues right now).

**Comment by timdeschryver** [comment]
Going to merge this since it's already better than the current grid. 
Feel free to create a follow up PR to align the baselines.

**Comment by timdeschryver** [comment]
@all-contributors please add @AldinRekic  for design

**Pull request merged**
