### PR TITLE
Updated React Router title

### PR DESCRIPTION
**Pull request by TOPOFGR**
Details:

-Changed `Reach` for `React`

### CODE REVIEW

**Comment by nickmccurdy** [comment]
We should probably update the URL too, right?

**Comment by TOPOFGR** [comment]
> We should probably update the URL too, right?

Yeah and the Sidebar too

**Comment by nickmccurdy** [comment]
Do you want to do that or would you like help?

**Comment by nickmccurdy** [comment]
I just realized this may be a mistake. We already have a page for React Router, this is for Reach Router which is a different library.

**Comment by TOPOFGR** [comment]
> I just realized this may be a mistake. We already have a page for React Router, this is for Reach Router which is a different library.

Ok, my bad. Sorry

**Comment by nickmccurdy** [comment]
No problem, thanks for contributing anyway

**Pull request closed without merging**
