### PR TITLE
Updated Nightwatch Logo sizing #633

### PR DESCRIPTION
**Pull request by hedgecox**
#633 Updated Nightwatch Logo to be 128x128

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Thank you!

**Comment by nickmccurdy** [comment]
@all-contributors add @hedgecox for docs

**Comment by nickmccurdy** [comment]
@hedgecox Also please let us know if you wanted to count this pull request for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) as there's some manual setup involved on our end

**Comment by hedgecox** [comment]
@nickmccurdy that would be great if you could, Thankyou!

**Comment by nickmccurdy** [comment]
I enabled the repository, but I'm not sure if it affects pull requests from before I enabled it. Can you check [your profile](https://hacktoberfest.digitalocean.com/profile) for this pull request?

**Pull request merged**
