### PR TITLE
fix: typo in cleanup link

### PR DESCRIPTION
**Pull request by cncolder**

### CODE REVIEW

**Comment by MatanBobi** [comment]
Hi @cncolder, thanks for putting this PR :)
Am I missing something here? the current version does lead to where it should lead..

**Comment by cncolder** [comment]
@MatanBobi Really? I try again, and it's 404.

Screen Recording 2020-11-10 at 00 34 37

**Comment by MatanBobi** [comment]
That's odd.
ezgif-3-aa0ad5496333

Do other links work for you?

**Comment by cncolder** [comment]
There are 3 similar links on this page. Another links work for me except `Cleanup`. 🤔 
```md
[`wrapper`](api.mdx#wrapper)
[`queries`](api.mdx#render-options)
[`Cleanup`](./api#cleanup)
```

**Comment by cncolder** [comment]
ah, if you nav from home page. that's ok.
but if you open [setup page](https://testing-library.com/docs/react-testing-library/setup/). you will see what happened.
because I come from google.

**Review by nickmccurdy — APPROVED** [review]
Confirmed fix

**Comment by nickmccurdy** [comment]
@all-contributors add @cncolder for docs

**Comment by MatanBobi** [comment]
@nickmccurdy I think we'll need to do that for all the mdx's links. I wanted to verify it a little by navigating directly as @cncolder suggested just didn't get the chance yet.

**Comment by nickmccurdy** [comment]
I verified the 3 links @cncolder mentioned on this page, before and after the changes. Did you want us to verify any other links or pages?

**Comment by MatanBobi** [comment]
> I verified the 3 links @cncolder mentioned on this page, before and after the changes. Did you want us to verify any other links or pages?

My bad, sorry. I was pretty sure I removed all the `.md` extensions but apparently I just changed them to `.mdx` in the migration process, my thoughts are all messed up 😅  sorry :)

**Comment by nickmccurdy** [comment]
It's alright. Is this done or should we make an issue to follow up more changes/verification?

**Comment by MatanBobi** [comment]
I think that we're good for now :) I'll have another look at it today but on first glance it looks good. Thanks!

**Pull request merged**
