### PR TITLE
docs: add note about throwing for multiple elements

### PR DESCRIPTION
**Pull request by kentcdodds**
Relevant: #253

### CODE REVIEW

**Comment by alexkrolick** [comment]
Let's also update the cheatsheet tables

**Comment by kentcdodds** [comment]
Done 👍

**Comment by alexkrolick** [comment]
Might want to add a blog post after release as well discussing 1) the new org, 2) the goals of the opencollective 3) the breaking changes (maybe that one separately)

**Comment by kentcdodds** [comment]
Agreed. We have a blog on this website right?

**Comment by alexkrolick** [comment]
Yep, just add a markdown file in this directory: https://github.com/testing-library/testing-library-docs/tree/master/website/blog

**Comment by kentcdodds** [comment]
Sweet. I'll get that written now.

**Comment by kentcdodds** [comment]
I think this is ready to be merged.

We can bikeshed on the blog post here: #87

**Pull request merged**
