### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Changed `react` to `React`.

### CODE REVIEW

**Comment by kentcdodds** [comment]
@all-contributors please add @huyenltnguyen for docs

**Comment by kentcdodds** [comment]
@all-contributors please add @huyenltnguyen for docs

**Comment by kentcdodds** [comment]
lol, I forgot you were already added @huyenltnguyen 😅

**Comment by huyenltnguyen** [comment]
@kentcdodds lol, thanks for the super quick review and merge! 👍 

Btw, do you think the error handler for this case could be improved, to add some more specific detail to the comment instead of a generic 'something went wrong'?

I'm happy to give it a stab.

**Pull request merged**
