### PR TITLE
docs: add blog post about new stuff

### PR DESCRIPTION
**Pull request by kentcdodds**

### CODE REVIEW

**Comment by kentcdodds** [comment]
I think we should add a section about native-testing-library. @bcarroll22, do you want to do that?

**Comment by bcarroll22** [comment]
Sorry @kentcdodds I just saw this. I see you've got a section in there about it now, do you still want me to add anything to it? I can't really think of anything, the only thing I could maybe see being helpful is the technical deep dive article I wrote a while back?

**Comment by kentcdodds** [comment]
I'll add the link. Thanks @bcarroll22!

**Comment by kentcdodds** [comment]
Sweet. This is ready to go!

**Pull request merged**
