### PR TITLE
Remove mention to Firefox extension in about.mdx

### PR DESCRIPTION
**Pull request by giovanniPepi**
Linked firefox extension was removed from the store; update the text to remove its mention

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Do we know why it was removed? Could we publish it again instead?

**Comment by giovanniPepi** [comment]
It seems that the previous attempts to get the extension on the store running were problematic, and @smeijer is not trying to upload it again so it's in an undefined state currently

https://github.com/testing-library/testing-playground/pull/327

https://github.com/testing-library/testing-playground/issues/344

**Comment by smeijer** [comment]
Copy from the developer hub:

> Approved by Add-ons Review Team about a year ago
> 
> This version has been screened and approved for the public. Keep in mind that other reviewers may look into this version in the future and determine that it requires changes or should be taken down.
> 
> Thank you!
> 
> Rejected by Add-ons Review Team 2 months ago
> 
> 1) Extensions defining a content security policy that allows eval ('unsafe-eval') are generally not allowed for security and performance reasons. ‘eval’ is only necessary in rare cases.
> - devtools/src/manifest.json line 24
> 
> In addition the following is required to complete the review:
> 
> 1) Please let us know to what file is '"sha256-6UcmjVDygSSU8p+3s7E7Kz8EG/ARhPADPRUm9P90HLM=" a reference for and how do you obtain it.
> - devtools/src/manifest.json line 24

I'm not sure if @tsuki42 has already attempted to retry, but I'm happy to add others to the Mozilla dev env as well. Just let me know your email address either here, or on [twitter dm](https://twitter.com/meijer_s), and I'll add you.

**Comment by tsuki42** [comment]
@smeijer Not yet. Still trying to figure out why they are unhappy about it.

**Review by eps1lon — APPROVED** [review]
We should remove it until the situation is figured out. It has not been resolved in over a month.

**Comment by bmulholland** [comment]
Closes #1134

**Comment by MatanBobi** [comment]
@all-contributors please add @giovanniPepi for docs :)

**Pull request merged**
