### PR TITLE
docs: fix missing space on support page

### PR DESCRIPTION
**Pull request by dustinsoftware**

### CODE REVIEW

**Comment by kentcdodds** [comment]
@all-contributors please add @dustinsoftware for content

**Comment by kentcdodds** [comment]
@all-contributors please add @dustinmyers for docs

**Comment by dustinsoftware** [comment]
@kentcdodds did you mean to add me? Looks like “dustinmyers” was added

**Comment by kentcdodds** [comment]
Whoops! Sorry! Thanks for saying something.

**Comment by kentcdodds** [comment]
@all-contributors please add @dustinsoftware for docs

**Comment by dustinmyers** [comment]
There is room for many Dustin's here 😂

**Pull request merged**
