### PR TITLE
feat: convert npm to yarn commands on docs

### PR DESCRIPTION
**Pull request by semoal**
Hey folks 👋

I've introduced this little plugin to introduce automatic conversion of npm commands to yarn.

### Demo:
Kapture 2021-03-17 at 14 55 52

### CODE REVIEW

**Comment by eps1lon** [comment]
Thanks for the suggestion. 

Since the change from npm to yarn is quite trivial and this plugin isn't trivial we just stick with `npm` for now.

**Comment by nickmccurdy** [comment]
Personally I think this would be worth reopening. New users don't necessarily know how to translate npm commands to yarn commands, and from a maintenance perspective this remark transformer makes it much easier to add both sets of commands to our docs (compared to manually adding Tabs, TabItems, and Yarn examples to each document).

**Comment by semoal** [comment]
Now, this is even easier... because Docusaurus ships the plugin I've implemented here but inside a module.
https://www.npmjs.com/package/@docusaurus/remark-plugin-npm2yarn

If you're all agree, I can adjust the pull request adding this module. 👍

**Comment by nickmccurdy** [comment]
That sounds like a good idea, let's reopen it to try it out.

**Comment by semoal** [comment]
@nickmccurdy Done mate!

Noticed one issue with one link:
> warn Docs markdown link couldn't be resolved: (dom-testing-library/api-helpers.mdx) in /Users/sergio.moreno/OSS/testing-library-docs/docs/preact-testing-library/learn.mdx for version current

But not sure where it should point, I can fix it if you give me some extra details

**Comment by eps1lon** [comment]
@semoal Could you rebase this? We're still interested in landing this.

**Review by timdeschryver — APPROVED** [review]
I opened a few pages and this looks good to me.

**Comment by eps1lon** [comment]
@all-contributors add @semoal for code

**Pull request merged**
