### PR TITLE
add stickers

### PR DESCRIPTION
**Pull request by kentcdodds**
These look awesome and were made by @vojtaholik

### CODE REVIEW

**Comment by kentcdodds** [comment]
@all-contributors please add @vojtaholik for design

**Comment by alexkrolick** [comment]
💯

**Comment by kentcdodds** [comment]
Sweet. Maintainers can find the stickers here:

- https://testing-library.com/img/stickers/angular-testing-library.pdf
- https://testing-library.com/img/stickers/cypress-testing-library.pdf
- https://testing-library.com/img/stickers/jest-dom.pdf
- https://testing-library.com/img/stickers/jest-native.pdf
- https://testing-library.com/img/stickers/native-testing-library.pdf
- https://testing-library.com/img/stickers/react-hooks-testing-library.pdf
- https://testing-library.com/img/stickers/react-testing-library.pdf
- https://testing-library.com/img/stickers/svelte-testing-library.pdf
- https://testing-library.com/img/stickers/testcafe-testing-library.pdf
- https://testing-library.com/img/stickers/testing-library.pdf
- https://testing-library.com/img/stickers/vue-testing-library.pdf

@alexkrolick and I are discussing things we can do with this, but if you want you can go ahead and make your own stickers on StickerMule. You can get 50 2x2 die cut stickers for $57: https://www.stickermule.com/products/die-cut-stickers

**Comment by afontcu** [comment]
This is great! 😍  Should the stickers, however, include the short name (`RTL`/`DTL`/`VTL` and so on) in order to make them recognizable?

**Comment by kentcdodds** [comment]
You can add them yourself if you like 👍

**Comment by benmonro** [comment]
are the PDFs with the project names under them available?

**Comment by kentcdodds** [comment]
Unfortunately not, but this should work for StickerMule:

63384828-eb15e900-c35c-11e9-8eef-3ac704c89868

Just crop out the one that you want from that and StickerMule should be able to make it look great :)

**Comment by vojtaholik** [comment]
@benmonro here's a PDF: https://cl.ly/e3f7a851e2f6 👀

**Pull request merged**
