### PR TITLE
docs: replaced url for queries page

### PR DESCRIPTION
**Pull request by shemExelate**
resolves https://github.com/testing-library/testing-library-docs/issues/803

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
Could you also add a redirect to the new page so that links from older versions of the docs and links from external pages work as well?

**Comment by shemExelate** [comment]
> Could you also add a redirect to the new page so that links from older versions of the docs and links from external pages work as well?

Correct me if I'm wrong but I think there is already a redirect for this page

https://github.com/testing-library/testing-library-docs/blob/ba1ae858d1362dc4e923f1b9915c9994dbc57655/netlify.toml#L58

**Review by eps1lon — APPROVED** [review]
> Correct me if I'm wrong but I think there is already a redirect for this page

@shemExelate That's confusing to me. The redirects are working. But on the currently deployed docs the link doesn't make sense at all:

In https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/#test-1-render-the-component-and-check-if-the-h1-value-is-correct "queries" links to https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/dom-testing-library/api-queries.mdx#byrole which obviously is 404.

But I guess this wasn't the original link but rather https://testing-library.com/docs/dom-testing-library/api-queries#byrole which does redirect. So at least links from externals should be good.

**Comment by eps1lon** [comment]
@all-contributors add @shemExelate for docs

**Pull request merged**
