### PR TITLE
Fix info about the Browser Extension 'Testing Playground'

### PR DESCRIPTION
**Pull request by wuarmin**

### CODE REVIEW

**Comment by MatanBobi** [comment]
Hi @wuarmin, thanks for taking the time to create this one :)
Could you please update the Firefox link to be in english instead of german?
Thanks!

**Comment by wuarmin** [comment]
@MatanBobi You're welcome.
I fixed the link.

**Review by MatanBobi — APPROVED** [review]
Looks good, thanks for this one!

**Comment by MatanBobi** [comment]
@all-contributors please add @wuarmin for docs :)

**Pull request merged**
